realodix/flarum-ext-indonesian

composer.json, locale/core.yml, locale/ext-flagrow-impersonate.yml, locale/ext-flagrow-users-list.yml, locale/ext-fof-ads.yml, locale/ext-fof-bazaar.yml, locale/ext-fof-byobu.yml, locale/ext-fof-custom-footer.yml, locale/ext-fof-split.yml, locale/ext-fof-upload.yml, locale/ext-oaklinq-reply2see.yml, locale/flarum-tags.yml, locale/validation.yml
https://github.com/flarum/lang-english
Digabung setelah Flarum beta 9 atau versi terbaru dari [flarum/lang-english](https://github.com/flarum/lang-english/releases) keluar.
=> Flarum Beta 9

README.md, composer.json, locale/core.yml, locale/flarum-markdown.yml
Digabungkan setelah Flarum [v0.1.0-beta.10](https://github.com/flarum/core/compare/v0.1.0-beta.9...v0.1.0-beta.10) telah dirilis.
Lihat https://github.com/flarum/lang-english/compare/v0.1.0-beta.9...master
=> Flarum v0.1.0-beta.10

README.md, locale/ext-fof-byobu.yml
Tunggu versi terbaru dirilis, di atas versi 0.3.4
Commit
- https://github.com/FriendsOfFlarum/byobu/commit/eba21cb39602a8e1aff6864c1a73fc0c27ebf6f8#diff-b33d460533a55cc7bc6acc9fd193dcf2
=> Update FriendsOfFlarum/byobu from 0.3.4 to 0.4.1

README.md
https://github.com/MichaelBelgium/flarum-profile-views/blob/v2.1.6/locale/en.yml
=> Update MichaelBelgium/flarum-profile-views v2.1.6

README.md, locale/ext-michaelbelgium-flarum-discussion-views.yml
https://github.com/MichaelBelgium/flarum-discussion-views/blob/v3.1.0/locale/en.yml
=> Update MichaelBelgium/flarum-discussion-views v3.1.0

README.md, locale/ext-fof-reactions.yml
https://github.com/FriendsOfFlarum/reactions/commits/master/resources/locale/en.yml
=> Update FriendsOfFlarum/reactions from 0.1.0 to 0.2.1

README.md, locale/ext-fof-subscribed.yml
https://github.com/FriendsOfFlarum/subscribed/blob/0.2.3/resources/locale/en.yml
=> Update FriendsOfFlarum/subscribed from 0.1.1 to 0.2.3

locale/core.yml
> Memperbaiki kalimat yang typo.
> Menambah/mengurangi kata-kata yang pas untuk di baca supaya luwes.
> Mengartikan (Subjek dan Body) email ke bahasa Indonesia.
=> Improve core.yml

README.md, composer.json, locale/core.yml, locale/flarum-tags.yml
https://github.com/flarum/lang-english
Digabung ketika Flarum v0.1.0-beta.13 sudah dirilis
=> Flarum v0.1.0-beta.13

locale/ext-jslirola-login2seeplus.yml
https://github.com/jslirola/flarum-ext-login2seeplus/blob/master/locale/en.yml
=> Add jslirola/flarum-ext-login2seeplus

README.md, locale/ext-clarkwinkelmann-watch-search.yml
https://github.com/clarkwinkelmann/flarum-ext-watch-search/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-watch-search

README.md, locale/ext-clarkwinkelmann-create-user-modal.yml
https://github.com/clarkwinkelmann/flarum-ext-create-user-modal/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-create-user-modal

README.md, locale/ext-clarkwinkelmann-first-post-approval.yml
https://github.com/clarkwinkelmann/flarum-ext-first-post-approval/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-first-post-approval

README.md, locale/ext-clarkwinkelmann-likes-received.yml
https://github.com/clarkwinkelmann/flarum-ext-likes-received/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-likes-received

README.md, locale/ext-clarkwinkelmann-emojionearea.yml
https://github.com/clarkwinkelmann/flarum-ext-emojionearea/blob/master/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-emojionearea

README.md, locale/ext-clarkwinkelmann-bookmarks.yml
https://github.com/clarkwinkelmann/flarum-ext-bookmarks/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-bookmarks

README.md, locale/ext-clarkwinkelmann-colorful-borders.yml
https://github.com/clarkwinkelmann/flarum-ext-colorful-borders/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-colorful-borders

README.md, locale/ext-clarkwinkelmann-group-invitation.yml
https://github.com/clarkwinkelmann/flarum-ext-group-invitation/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-group-invitation

README.md, locale/ext-clarkwinkelmann-passwordless.yml
https://github.com/clarkwinkelmann/flarum-ext-passwordless/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-passwordless

README.md, locale/ext-clarkwinkelmann-popular-discussion-badge.yml
https://github.com/clarkwinkelmann/flarum-ext-popular-discussion-badge/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-popular-discussion-badge

README.md, locale/ext-clarkwinkelmann-see-past-first-post.yml
https://github.com/clarkwinkelmann/flarum-ext-see-past-first-post/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-see-past-first-post

README.md, locale/ext-clarkwinkelmann-silent-mailchimp.yml
https://github.com/clarkwinkelmann/flarum-ext-silent-mailchimp/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-silent-mailchimp

README.md, locale/ext-clarkwinkelmann-status.yml
https://github.com/clarkwinkelmann/flarum-ext-status/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-status

README.md, locale/ext-clarkwinkelmann-who-read.yml
https://github.com/clarkwinkelmann/flarum-ext-who-read/blob/master/resources/locale/en.yml
=> Add clarkwinkelmann/flarum-ext-who-read

README.md, locale/ext-the-turk-diff.yml
https://github.com/the-turk/flarum-diff/blob/master/locale/en.yml
=> Add the-turk/flarum-diff

README.md, composer.json, locale/ext-fof-username-request.yml
https://github.com/FriendsOfFlarum/username-request/compare/0.4.0...0.4.1
=> Fof/username request v0.4.1

README.md, composer.json, locale/core.yml, locale/flarum-nicknames.yml, locale/flarum-tags.yml
https://github.com/flarum/lang-english/compare/v0.1.0-beta.14...v0.1.0-beta.15
=> Flarum 0.1.0-beta.15

locale/fof-subscribed.yml
- [FriendsOfFlarum/subscribed/compare/1.0.2...1.1.2#diff-2fc8643](https://github.com/FriendsOfFlarum/subscribed/compare/1.0.2...1.1.2#diff-2fc8643b9ebb3b1f9f8f8064804db6bfa8cce56e4f30fb244a132cc04bad15a9)
- https://github.com/realodix/flarum-ext-indonesian/commit/7e8e78ffb8f72beb06d27db572cc4060a6748776
=> fof/subscribed v1.1.2

README.md, locale/fof-upload.yml
- https://github.com/FriendsOfFlarum/upload/compare/1.1.0...1.2.3#diff-2fc8643b9ebb3b1f9f8f8064804db6bfa8cce56e4f30fb244a132cc04bad15a9
- https://github.com/FriendsOfFlarum/upload/blob/d1f0e4bae11ce12f4d1f6482b380e48f345a8dd3/resources/locale/en.yml
=> fof/upload v1.2.3
